# DRSorterのサンプル設定ファイル

# 共通設定
common:
  still_type: "スチル"  # メディアプールでの画像タイプ名。英語環境の場合は"Still"等に変更
  rotation_angle: 90.0  # 縦写真の回転角度

# デフォルト設定
default:
  power_grade: "D:/DaVinci Resolve/PowerGrade/Default.drx"  # デフォルトのPowerGrade
  distortion: 0  # デフォルトのレンズ補正値

# アスペクト比別のportrait_scale設定
aspect_ratios:
  "4:3":
    portrait_scale: 1.374  # 4:3の縦写真用スケール値
  "3:2":
    portrait_scale: 1.51   # 3:2の縦写真用スケール値

# カメラ機種別のPowerGrade設定
cameras:
  "DC-GH7":  # カメラモデル名（Camera TC Type）
    power_grade: "D:/DaVinci Resolve/PowerGrade/GH7 Normalize.drx"

# レンズ別のDistortion設定
lenses:
  "OLYMPUS M.17mm F1.8":  # レンズ名（Lens Type）
    distortion: 0.13  # レンズ補正値
